-- Warehouse (keep it cheap)
CREATE WAREHOUSE IF NOT EXISTS WH_CHURN_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS CHURN_DB;

CREATE SCHEMA IF NOT EXISTS CHURN_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CHURN_DB.STG;
CREATE SCHEMA IF NOT EXISTS CHURN_DB.ANALYTICS;
